kind: pipeline
type: kubernetes
name: build-base-image
trigger:
  branch:
    - base
  event:
    - push
steps:
  - name: build-and-push-base
    image: plugins/docker
    settings:
      registry: gitea-http.gitea.svc.cluster.local:3000
      repo: gitea-http.gitea.svc.cluster.local:3000/vinoxm/node-server-base
      insecure: true
      dockerfile: Dockerfile.base
      username:
        from_secret: GITEA_USERNAME
      password:
        from_secret: GITEA_PASSWORD
      tags:
        - latest
---
kind: pipeline
type: kubernetes
name: build-and-deploy
trigger:
  event:
    - tag
steps:
  - name: publish-image
    image: plugins/docker
    settings:
      registry: gitea-http.gitea.svc.cluster.local:3000
      repo: gitea-http.gitea.svc.cluster.local:3000/vinoxm/node-server
      insecure: true
      username:
        from_secret: GITEA_USERNAME
      password:
        from_secret: GITEA_PASSWORD
      tags:
        - ${DRONE_TAG}
        - latest
    when:
      ref:
        - refs/tags/v*
  - name: update-deployment-yaml
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: argocd_deploy_key
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keyscan -p 22 gitea-ssh.gitea.svc.cluster.local >> ~/.ssh/known_hosts
      - git clone ssh://git@gitea-ssh.gitea.svc.cluster.local/VinoxM/k3s-deployments.git
      - cd k3s-deployments
      - |
        sed -i "s|image: .*node-server:.*|image: 192.168.31.110:30003/vinoxm/node-server:${DRONE_TAG}|g" node-server/deployment.yaml
      - git config user.name "Drone CI"
      - git config user.email "drone@vinoxm.cloud"
      - git add node-server/deployment.yaml
      - |
        git commit -m "chore: update node-server image to ${DRONE_TAG} [skip ci]"
      - git push origin main
    when:
      ref:
        - refs/tags/v*
  - name: trigger-argocd-sync
    image: gitea.vinoxm.cloud/library/argocli:3.2.3
    environment:
      ARGOCD_SERVER: argocd-server.argocd.svc.cluster.local
      ARGOCD_AUTH_TOKEN:
        from_secret: argocd_token
    commands:
      - argocd app get node-server-deployment --refresh --server $ARGOCD_SERVER --insecure --auth-token $ARGOCD_AUTH_TOKEN
      - argocd app sync node-server-deployment --server $ARGOCD_SERVER --insecure --auth-token $ARGOCD_AUTH_TOKEN
      - argocd app wait node-server-deployment --server $ARGOCD_SERVER --insecure --auth-token $ARGOCD_AUTH_TOKEN
    when:
      ref:
        - refs/tags/v*