FROM gitea.vinoxm.art/library/node:24.12-puppeter

ENV http_proxy=http://192.168.31.100:7890 \
    https_proxy=http://192.168.31.100:7890

WORKDIR /app

COPY package*.json ./

RUN npm config set registry https://mirrors.cloud.tencent.com/npm/ && npm install

ENV http_proxy="" \
    https_proxy=""