logger:
  level: info
  savePath: /home/maou/.github/node-server/log
sqlite:
  defaultDB: rss
  dbPath: "@/db"
  executionPath: "@/resource/execution"
server:
  port: 8800
  cors: true
axios:
  proxy:
    protocol: http
    host: gateway.vinoxm.lan
    port: 7890
api:
  requestBodyLimit: 2 * 1024 * 1024
  apiDisabled:
    - /common/doNothing
  allowHosts:
    - api: /summary/*
      hosts: ["*-coder.vinoxm.cloud", "server.vinoxm.art"]
  filterDisabled: []
  needAuth:
    - /rss(/v2)?/[(?!get)|Matchers]*$
    - /rss/subscribe/*
    - /rss/[copyright|link]/[add|edit|del].*
    - /rss/result/*
    - /rss/regex/*
  tokenBucket:
    config:
      enable: true
      initSize: 10
      maxSize: 100
      rate: 0.5
    needToken:
      - /rss(/v2)?/get((?!/|Matchers).)*$
      - /rss/tracker/getAll
  ipBlocker:
    enable: true
    maxInterval: 1000 * 60
    maxCount: 100
    blockTime: 1000 * 60 * 60 * 24
    blockIgnore:
      - /common/*
      - /rss/subscribe/*
      - /rss/[copyright|link]/[add|edit|del].*
      - /rss/[subtitle|episode|fonts]/*
      - /rss/result/*
      - /rss/regex/*
      - /rss/task/*
      - /media/*
      - /rss/v2/getRssCardFailedViews
sse:
  disabled:
    - barrage
schedule:
  rssSubscribe:
    enable: true
    corn: 0 7/30 * * * *
  clashSubscribe:
    enable: true
    corn: 0 0 0/12 * * *
  ipBlockerClean:
    enable: true
    corn: 0 0/10 * * * *
  kuroGameSign:
    enable: true
    corn: 0 0 0 * * *
  storageSummary:
    enable: true
    corn: 0 0 0/2 * * *
  rssSubscribeVector:
    enable: true
    corn: 0 30 0/2 * * *
  biliveStreamAutoSync:
    enable: true
    corn: 0 0 4 * * *
rss:
  convertMkvToMp4:
    enable: false
  semanticSearch:
    similarity: 0.7
  subscribeHandler:
    parallelNum: 3
    everyHandleCount: 30
    handleDelay: 5000
  regex:
    historyLimit: 20
  matchers:
    - name: 末日动漫
      source: https://share.acgnx.se/
      regex: .*acgnx.*
      keyword: true
      match: https://share.acgnx.se/rss.xml?sort_id=0&keyword=#{keyword}
    - name: 动漫花园
      source: https://share.dmhy.org/
      regex: .*dmhy.*
      keyword: true
      match: https://share.dmhy.org/topics/rss/rss.xml?keyword=#{keyword}
  awaitRssUpdating:
    - /rss/[copyright|link|result|subscribe]/[add|edit|replace|update].*
    - /rss/subscribe/[subTest|setFin]
  episodeMatches:
    - .*?\[([0-9]{1,4}(\.5)?)(v[0-3])?\].*
    - .*?[-～] ([0-9]{1,4}(\.5)?)(v[0-3])? .*
    - .*?第([0-9]{1,4}(\.5)?)(v[0-3])?(集|话)(v[0-3])?.*
    - .*?【([0-9]{1,4}(\.5)?)(v[0-3])?】.*
    - .*? ([0-9]{1,4}(\.5)?)(v[0-3])? .*
    - .*?E([0-9]{1,4}(\.5)?)(v[0-3])? .*
    - .*?[S[1-9]{1}E([0-9]{1,4}(\.5)?)(v[0-3])?].*
    - .*?★([0-9]{1,4}(\.5)?)(v[0-3])?★.
    - .*?\.S[0-9]{1,2}E([0-9]{1,3})\.
  animeExtRegex: ^\.(mp4|avi|flv|mkv|mov|wmv|rmvb|3gp|mpeg|mpg)$
  subtitleExtRegex: ^\.(srt|vtt|ass)$
  subtitleMatchers:
    - .*?(JPTC|JPSC).*
    - .*?(cht|chs).*
    - .*?(tc|sc).*
clash:
  path:
    deployment: /mnt/data/.config/mihomo/conf
    persistence: /mnt/data/.config/clash
    subscription: /mnt/data/.config/clash/subscription
    concat: /mnt/data/.config/clash/concat
    backup: /mnt/data/.config/clash/backup
    tailscale: /mnt/data/.config/clash/tailscale
  deployment:
    excludeKeys:
      - "external-controller"
      - "external-ui"
      - "secret"
    mixin:
      external-controller: 0.0.0.0:9900
      external-ui: /shared_media/.config/mihomo/conf/dashboard/public
      secret: 9fbcc5b16365b44ac6433eea9ce02adb323b1338ec1e2e7dbd68073765b9d03e
      socks-port: 7890
      redir-port: 7890
  subscription:
    sources:
      - url: https://is.domainforsub.work/sub/553e7c3da73124ed
        label: Cloud
        isDefault: true
  concat:
    proxyFilters:
      - "官网"
      - "二手倒卖"
      - "试用"
      - "重大漏洞"
      - "备用"
      - "登录"
      - "工作室"
    proxyGroupFilters:
      - "🥀Special Traffic - Hanime1 Download"
    fallbackUrl: "http://www.gstatic.com/generate_204"
    groupMapping:
      JP: ["日"]
      HT: ["港", "台"]
      KR: ["韩"]
  backup:
    fileLimit: 10
statistics:
  scanOptions:
    - dbName: rss
      tables:
        - tableName: rss_episode
          linkColumn: minio_link
          sizeColumn: object_size
          matchers:
            - status = 1
        - tableName: rss_episode_subtitle
          linkColumn: minio_link
          sizeColumn: object_size
          matchers:
            - status = 2
        - tableName: rss_fonts
          linkColumn: minio_link
          sizeColumn: object_size
    - dbName: media
      tables:
        - tableName: video_minio
          linkColumn: link
          sizeColumn: object_size
          matchers:
            - status = 3
  bucketUsage:
    statQueryBatch: 10
    backfillBatch: 100
    scanBatchSize: 2000
qdrant:
  client:
    host: qdrant.vinoxm.art
    port: 443